#! /bin/python3
# -*- coding: Utf-8 -*

import sys
from bombyx_calculation import calculation_with_given_k, calculation_with_initial_generation

HELP_STR = """USAGE
\t./106bombyx n [k | i0 i1]

DESCRIPTION
\tn\tnumber of first generation individuals
\tk\tgrowth rate from 1 to 4
\ti0\tinitial generation (included)
\ti1\tfinal generation (included)"""

def error_check(argc: int, argv: list):
    if argc not in (3, 4):
        sys.exit(84)
    if not str(argv[1]).isdigit():
        sys.exit(84)
    if argc == 3:
        try:
            k = float(argv[2])
            if (1 <= k <= 4) is False:
                raise ValueError
        except ValueError:
            sys.exit(84)
    else:
        if not str(argv[2]).isdigit() or not str(argv[3]).isdigit():
            sys.exit(84)
        if int(argv[3]) < int(argv[2]):
            sys.exit(84)

def main(argc: int, argv: list):
    if argc == 2 and argv[1] == "-h":
        print(HELP_STR)
        return 0
    error_check(argc, argv)
    args = tuple(float(value) for value in argv[1:])
    function_for_calculation = {
        2: calculation_with_given_k,
        3: calculation_with_initial_generation
    }
    function_for_calculation[len(args)](*args)
    return 0

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv.copy()))
